In [1]:
import numpy as np
my_list = ([1,2,3],[4,5,6],[6,7,8])


In [3]:
np.arange(1,5) ## (start,stop)

array([1, 2, 3, 4])

In [5]:
np.arange(1,6,2) #(start,stop,step)

array([1, 3, 5])

In [6]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
a=np.zeros((4,4))   ## 2D (())
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
a=a.astype(int)  # int conversion
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.eye(5)   # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.linspace(0,5,20)  # equally spaced points btw (start,stop,#)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [15]:
np.random.rand(5)  # random 5 numbers

array([0.13568716, 0.99958723, 0.08865945, 0.90145397, 0.07129375])

In [16]:
np.random.randn(5) ## values follows normal distr.

array([-1.71983503,  1.16153873,  0.72043627, -1.49842532,  0.00359041])

In [17]:
np.random.rand(4,4)

array([[0.56674331, 0.39618805, 0.10367369, 0.90443615],
       [0.99607983, 0.63563481, 0.52470711, 0.92524837],
       [0.52115576, 0.21675749, 0.07499724, 0.49467035],
       [0.48687146, 0.93835648, 0.77772241, 0.64588222]])

In [18]:
np.random.randint(1,50)

44

In [19]:
np.random.randint(1,50,10)

array([23, 11,  1, 11, 24,  6,  7,  5, 41, 23])

In [21]:
array=([4,3,44,12,14,5,66,78])


In [22]:
arr = np.random.randint(1,100,10)
print(arr)
arr.shape

[67 41 29 93 10 76 29 46 29 37]


(10,)

In [23]:
arr.reshape(5,2)

array([[67, 41],
       [29, 93],
       [10, 76],
       [29, 46],
       [29, 37]])

In [24]:
arr.reshape(10,1)

array([[67],
       [41],
       [29],
       [93],
       [10],
       [76],
       [29],
       [46],
       [29],
       [37]])

In [25]:
arr.max()

93

In [26]:
arr.min()

10

In [27]:
arr.argmin()

4

In [29]:
arr.argmax()

3

In [30]:
arr_id = np.arange(0,10)

In [31]:
arr_id

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr_id[:4]

array([0, 1, 2, 3])

In [33]:
arr_id[4:]

array([4, 5, 6, 7, 8, 9])

In [34]:
arr2 = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [35]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [37]:
arr2[2]

array([6, 7, 8])

In [38]:
arr2[0,0]

1

In [39]:
arr2[1:1]

array([], shape=(0, 3), dtype=int64)

In [40]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [41]:
arr[:2]

array([67, 41])

In [43]:
arr2[1:,:2]

array([[4, 5],
       [6, 7]])

In [44]:
ar=np.arange(5,15)

In [45]:
ar>8

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
bool_ar=ar>8

In [47]:
ar[bool_ar]

array([ 9, 10, 11, 12, 13, 14])

In [48]:
ar[ar>7]

array([ 8,  9, 10, 11, 12, 13, 14])

In [49]:
arr_new = np.arange(100).reshape(25,4)
arr_new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])